# Простые типы, комментарий

word: Some string    # без кавычек
num: 2009       # число
none: null      # None
bool: true      # Bool

# Список одной строкой
lst1: [буквы, 123, null]

# Многострочный вариант списка
lst2:
    - буквы   # тут возможны комментарии
    # и тут тоже
    - 123
    - null

# Словарь в одну строку
dic1: {word : буквы, num : 123, none : null}

# Многострочный словарь
dic2:
    word: буквы
    num: 123
    none: null

# Длинная строка, переносы удаляются
big_str1: >
    Hello
    Hi
    Greatings

# Длинная строка, переносы сохраняются
big_str2: |
    Hello
    Hi
    Greatings

# Вложенности
langs:
    - XML:
        читабельность: низкая
        использование: тяжелые парсеры
        назначение: обмен данными
    - YAML:
        читабельность: высокая
        использование: простота
        назначение: конфиг файлы
